name: Question
description: Ask a question or seek help
title: "[Question]: "
labels: ["question"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for asking a question! We're here to help.

  - type: textarea
    id: question
    attributes:
      label: Question
      description: What would you like to know?
      placeholder: Ask your question here...
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context
      description: Provide any relevant context about your question
      placeholder: |
        - What are you trying to accomplish?
        - What have you tried so far?
        - Any relevant code snippets or error messages?

  - type: dropdown
    id: area
    attributes:
      label: Area
      description: Which area does your question relate to?
      options:
        - Setup/Installation
        - Frontend Development
        - Backend Development
        - API Usage
        - Authentication
        - AI Services
        - Docker
        - Database
        - Deployment
        - Documentation
        - Other
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Version/Environment
      description: Your environment details (if relevant)
      placeholder: e.g., Node v18, Docker, Local development

  - type: textarea
    id: research
    attributes:
      label: Research Done
      description: What have you already checked?
      placeholder: |
        - [ ] Checked the documentation in docs/
        - [ ] Searched existing issues
        - [ ] Checked GitHub Discussions
        - [ ] Tried troubleshooting steps

  - type: checkboxes
    id: checks
    attributes:
      label: Checklist
      options:
        - label: I have searched existing issues and discussions
          required: true
        - label: I have checked the documentation
          required: true
        - label: I have provided relevant context
          required: true
